### ISSUE TITLE
Ubuntu 20.04 LTS combo boxes empty

### ISSUE THREAD

**Issue by markbrule** [michaelgoetze/LogDog#12]
I've been using LogDog on my Windows browser without a problem. I've now switched over to a linux (Ubuntu 20.04) desktop running Chrome (Version 92.0.4515.107 (Official Build) (64-bit)) and I'm seeing that the combo boxes for the game, players, etc are all blank. In the screen shot below I've actually got two logs stored.

Hopefully you're still maintaining this - this extension has been super useful for me. I appreciate it very much!

![LogDog-ubuntu-capture](https://user-images.githubusercontent.com/8799594/129468580-e8d437a5-7e88-4261-a04c-85938826d21d.png)

**Comment by michaelgoetze** [comment]
I will try to look into into it. I'll have to install an ubuntu virtual machine.

**Comment by michaelgoetze** [comment]
I found the problem and could fix it. It will take a while until this is incorporated in the Chrome webstore version. The problem was that a file was not loaded into the extension in Linux. This was because I had an uppercase instead of a lowercase letter in a script-filename... 
Anyway it is fixed with v0.0.16 and you can simply install from this repository:

> To install this extension, download this repository as ZIP-file and extract the content anywhere on your PC, where it will stay (So the Desktop is maybe not the best place). Use Chrome and go to the adress:
>
>chrome://extensions
>
>and activate developer mode in the top right corner of this window. Then use the button "load unpacked extension" and navigate to the unzipped folder that contains all the extension files and select this folder. Make sure that the extension is active (small slider switch) and you should see the LogDog-icon next to your adress bar (it might be hidden, decrease the size of your adress bar to see hidden extensions.

It would be great if you could rate LogDog on the Chrome Webstore. It might increase visibility. Thanks!

**Comment by markbrule** [comment]
Awesome, thanks a bunch!

**Comment by markbrule** [comment]
Extension installed from Zipfile, works like a charm.

Review in the Chrome Webstore.

Thanks again.
